export const GET_USER_DETAILS_SUCCESS = 'kari4me/GET_USER_DETAILS_SUCCESS';
export type GET_USER_DETAILS_SUCCESS = typeof GET_USER_DETAILS_SUCCESS;

export const GET_USER_DETAILS_FAILURE = 'kari4me/GET_USER_DETAILS_FAILURE';
export type GET_USER_DETAILS_FAILURE = typeof GET_USER_DETAILS_FAILURE;

export const EDIT_USER_DETAILS_SUCCESS = 'kari4me/EDIT_USER_DETAILS_SUCCESS';
export type EDIT_USER_DETAILS_SUCCESS = typeof EDIT_USER_DETAILS_SUCCESS;

export const EDIT_USER_DETAILS_FAILURE = 'kari4me/EDIT_USER_DETAILS_FAILURE';
export type EDIT_USER_DETAILS_FAILURE = typeof EDIT_USER_DETAILS_FAILURE;

export const LOG_OUT_USER = 'kari4me/LOG_OUT_USER';
export type LOG_OUT_USER = typeof LOG_OUT_USER;
