export const GET_USER_ROLES_SUCCESS = 'kari4me/user-roles/GET_USER_ROLES_SUCCESS';
export type GET_USER_ROLES_SUCCESS = typeof GET_USER_ROLES_SUCCESS;

export const DELETE_USER_ROLES_SUCCESS = 'kari4me/user-roles/DELETE_USER_ROLES_SUCCESS';
export type DELETE_USER_ROLES_SUCCESS = typeof DELETE_USER_ROLES_SUCCESS;

export const EDIT_USER_ROLES_SUCCESS = 'kari4me/user-roles/EDIT_USER_ROLES_SUCCESS';
export type EDIT_USER_ROLES_SUCCESS = typeof EDIT_USER_ROLES_SUCCESS;

export const CREATE_USER_ROLES_SUCCESS = 'kari4me/user-roles/CREATE_USER_ROLES_SUCCESS';
export type CREATE_USER_ROLES_SUCCESS = typeof CREATE_USER_ROLES_SUCCESS;
