export const RESET_PASSWORD_REQUEST = 'kari4me-web/authentication/RESET_PASSWORD_REQUEST';
export type RESET_PASSWORD_REQUEST = typeof RESET_PASSWORD_REQUEST;

export const RESET_PASSWORD_SUCCESS = 'kari4me-web/authentication/RESET_PASSWORD_SUCCESS';
export type RESET_PASSWORD_SUCCESS = typeof RESET_PASSWORD_SUCCESS;

export const RESET_PASSWORD_FAILURE = 'kari4me-web/authentication/RESET_PASSWORD_FAILURE';
export type RESET_PASSWORD_FAILURE = typeof RESET_PASSWORD_FAILURE;

export const FORGOT_PASSWORD_REQUEST = 'kari4me-web/authentication/FORGOT_PASSWORD_REQUEST';
export type FORGOT_PASSWORD_REQUEST = typeof FORGOT_PASSWORD_REQUEST;

export const FORGOT_PASSWORD_SUCCESS = 'kari4me-web/authentication/FORGOT_PASSWORD_SUCCESS';
export type FORGOT_PASSWORD_SUCCESS = typeof FORGOT_PASSWORD_SUCCESS;

export const FORGOT_PASSWORD_FAILURE = 'kari4me-web/authentication/FORGOT_PASSWORD_FAILURE';
export type FORGOT_PASSWORD_FAILURE = typeof FORGOT_PASSWORD_FAILURE;
