FROM node:carbon

LABEL maintainer="Francis Masha"

# Copy the current directory contents into the container at /app
COPY . /app

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in package.json
RUN yarn install

# Expose port 3000 for accessing  the app
EXPOSE 3000

# Run app when the container launches
CMD ["yarn", "start"]
